### PR TITLE
Run Swing code on the Swing eventpool and Minecraft code on the appropriate MC thread to avoid crashes

### PR DESCRIPTION
**Pull request by eigenraven**

### CODE REVIEW

**Comment by Glease** [comment]
Can you give some pointers on what meaningful content you have actually changed? it's really hard to know what you are actually changing if you mix style change and content change, and you are changing like 100 files.

**Comment by eigenraven** [comment]
Look at the first commit only, second one is the spotless changes, first one is fixing various "potential bug" category warnings from intellij, wrapping calls to swing functions in SwingUtilities.invokeLater and a similar mechanism that can schedule world-modifying calls on the main mc thread in the tick handler. I see the import fixup also got commited there in some files (probably when I was autofixing missing generic parameters via the intellij quickfixes), but that's easy to skip through.

**Comment by Glease** [comment]
Your first commit changes over a hundred files either way.

**Comment by eigenraven** [comment]
I have reordered the commits to put spotless first, it makes the diffs much more readable now. Also split threading fixes from other misc warning fixes.

**Review by Glease — APPROVED** [review]
seems good now.

**Pull request merged**
